# Generated by Django 4.1.5 on 2023-01-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ticked_option', models.CharField(blank=True, max_length=10, null=True)),
                ('cat_1_prize', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_next_jackpot', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduler', models.DateTimeField(blank=True, null=True)),
                ('run_every', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
