# Generated by Django 4.1.5 on 2023-01-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ball0', models.CharField(max_length=255)),
                ('ball1', models.CharField(max_length=255)),
                ('ball2', models.CharField(max_length=255)),
                ('ball3', models.CharField(max_length=255)),
                ('ball4', models.CharField(max_length=255)),
                ('ball5', models.CharField(max_length=255)),
                ('bonus_ball', models.CharField(max_length=255)),
                ('draw_datetime', models.CharField(max_length=255)),
                ('estimated_next_jackpot_balls_left', models.CharField(max_length=255)),
                ('estimated_next_jackpot', models.CharField(max_length=255)),
                ('cat_2_prize', models.CharField(max_length=255)),
                ('cat_3_prize', models.CharField(max_length=255)),
                ('cat_4_prize', models.CharField(max_length=255)),
                ('cat_5_prize', models.CharField(max_length=255)),
                ('cat_6_prize', models.CharField(max_length=255)),
                ('cat_7_prize', models.CharField(max_length=255)),
                ('cat_8_prize', models.CharField(max_length=255)),
                ('cat_1_winners', models.CharField(max_length=255)),
                ('cat_2_winners', models.CharField(max_length=255)),
                ('cat_3_winners', models.CharField(max_length=255)),
                ('cat_4_winners', models.CharField(max_length=255)),
                ('cat_5_winners', models.CharField(max_length=255)),
                ('cat_6_winners', models.CharField(max_length=255)),
                ('cat_7_winners', models.CharField(max_length=255)),
                ('cat_8_winners', models.CharField(max_length=255)),
            ],
        ),
    ]
