# Generated by Django 4.1.5 on 2023-01-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='draw_datetime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='draw_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
