# Generated by Django 4.1.5 on 2023-01-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraper',
            old_name='estimated_next_jackpot',
            new_name='cat_9_winners',
        ),
        migrations.RenameField(
            model_name='scraper',
            old_name='estimated_next_jackpot_balls_left',
            new_name='n_MaxMillions',
        ),
        migrations.AddField(
            model_name='scraper',
            name='sales',
            field=models.CharField(default=100, max_length=255),
        ),
    ]
