# Generated by Django 4.1.5 on 2023-01-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_estimated_next_jackpot_scraper_cat_9_winners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='cat_1_prize',
            field=models.CharField(default=100, max_length=255),
            preserve_default=False,
        ),
    ]
