# Generated by Django 4.1.5 on 2023-01-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_scraper_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
