# Generated by Django 4.1.5 on 2023-01-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_scraper_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='cat_1_prize',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_1_winners',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_2_prize',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_2_winners',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_3_prize',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_3_winners',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_4_prize',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_4_winners',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_5_prize',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_5_winners',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_6_prize',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_6_winners',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_7_prize',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_7_winners',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_8_prize',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_8_winners',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cat_9_winners',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
