# Generated by Django 4.1.5 on 2023-01-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_scraper_cat_1_prize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='id',
        ),
        migrations.AlterField(
            model_name='scraper',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
