# Generated by Django 4.1.5 on 2023-01-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_scraper_id_alter_scraper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='estimated_next_jackpot',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='ball0',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='ball1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='ball2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='ball3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='ball4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='ball5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='bonus_ball',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='draw_datetime',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='n_MaxMillions',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='sales',
            field=models.CharField(default=100, max_length=255, null=True),
        ),
    ]
