# Generated by Django 4.1.5 on 2023-01-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_scraper_estimated_next_jackpot_alter_scraper_ball0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='ticked_option',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
