# Generated by Django 4.1.5 on 2023-01-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_scraper_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='run_every',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
