# Generated by Django 4.1.5 on 2023-01-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_scraper_run_every'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='run_every',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
